//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Problem Problem Details response based on RFC 7807.
type Problem struct {
	// Detail Example: Requested resource does not exist.
	Detail *string `json:"detail,omitempty"`

	// Instance Example: urn:moco:request:11111111-1111-4111-8111-111111111111
	Instance *string `json:"instance,omitempty"`

	// Status Example: 404
	Status int32 `json:"status"`

	// Title Example: Not Found
	Title string  `json:"title"`
	Type  *string `json:"type,omitempty"`
}

// Secret Secret metadata and base64-encoded value.
type Secret struct {
	// CreatedAt Example: 2026-08-25T12:00:00Z
	CreatedAt time.Time `json:"createdAt"`

	// Path Returned item path uses slash-delimited segments and forbids empty, `.`, and `..` segments.
	//
	// Example: prod/db/password
	Path string `json:"path"`

	// UpdatedAt Example: 2026-08-25T12:00:00Z
	UpdatedAt time.Time `json:"updatedAt"`

	// Value Base64-encoded secret value.
	//
	// Example: c2VjcmV0
	Value []byte `json:"value"`
}

// SecretList Secret metadata matching a prefix; values are never included.
type SecretList struct {
	// Secrets Example: [{"createdAt":"2026-08-25T12:00:00Z","path":"prod/db/password","updatedAt":"2026-08-25T12:00:00Z"}]
	Secrets []SecretMetadata `json:"secrets"`
}

// SecretMetadata Secret identity and lifecycle metadata without its value.
type SecretMetadata struct {
	// CreatedAt Example: 2026-08-25T12:00:00Z
	CreatedAt time.Time `json:"createdAt"`

	// Path Metadata path uses slash-delimited segments and forbids empty, `.`, and `..` segments.
	//
	// Example: prod/db/password
	Path string `json:"path"`

	// UpdatedAt Example: 2026-08-25T12:00:00Z
	UpdatedAt time.Time `json:"updatedAt"`
}

// SecretWrite Base64-encoded secret value to store at the query path.
type SecretWrite struct {
	// Value Base64-encoded value accepted for storage.
	//
	// Example: c2VjcmV0
	Value []byte `json:"value"`
}

// Tenant Tenant identity and lifecycle metadata.
//
// Example: {"createdAt":"2026-08-25T12:00:00Z","id":"11111111-1111-4111-8111-111111111111","name":"production","updatedAt":"2026-08-25T12:00:00Z"}
type Tenant struct {
	// CreatedAt Example: 2026-08-25T12:00:00Z
	CreatedAt time.Time `json:"createdAt"`

	// Id Example: 11111111-1111-4111-8111-111111111111
	Id openapi_types.UUID `json:"id"`

	// Name Example: production
	Name string `json:"name"`

	// UpdatedAt Example: 2026-08-25T12:00:00Z
	UpdatedAt time.Time `json:"updatedAt"`
}

// TenantCreate Fields accepted when creating a tenant.
type TenantCreate struct {
	// Name Example: production
	Name string `json:"name"`
}

// TenantUpdate Fields accepted when updating a tenant.
type TenantUpdate struct {
	// Name Example: platform
	Name string `json:"name"`
}

// Vault Tenant-scoped vault identity and lifecycle metadata.
type Vault struct {
	// CreatedAt Example: 2026-08-25T12:00:00Z
	CreatedAt time.Time `json:"createdAt"`

	// Id Example: 22222222-2222-4222-8222-222222222222
	Id openapi_types.UUID `json:"id"`

	// Name Example: application
	Name string `json:"name"`

	// TenantId Example: 11111111-1111-4111-8111-111111111111
	TenantId openapi_types.UUID `json:"tenantId"`

	// UpdatedAt Example: 2026-08-25T12:00:00Z
	UpdatedAt time.Time `json:"updatedAt"`
}

// VaultCreate Fields accepted when creating a vault.
type VaultCreate struct {
	// Name Example: application
	Name string `json:"name"`
}

// VaultUpdate Fields accepted when updating a vault.
type VaultUpdate struct {
	// Name Example: platform
	Name string `json:"name"`
}

// SecretPath defines model for SecretPath.
type SecretPath = string

// SecretPrefix defines model for SecretPrefix.
type SecretPrefix = string

// TenantId defines model for TenantId.
type TenantId = openapi_types.UUID

// VaultId defines model for VaultId.
type VaultId = openapi_types.UUID

// BadRequest Problem Details response based on RFC 7807.
type BadRequest = Problem

// Conflict Problem Details response based on RFC 7807.
type Conflict = Problem

// Forbidden Problem Details response based on RFC 7807.
type Forbidden = Problem

// InternalError Problem Details response based on RFC 7807.
type InternalError = Problem

// NotFound Problem Details response based on RFC 7807.
type NotFound = Problem

// Unauthorized Problem Details response based on RFC 7807.
type Unauthorized = Problem

// DeleteSecretParams defines parameters for DeleteSecret.
type DeleteSecretParams struct {
	// Path Required slash-delimited item path; empty, `.`, and `..` segments are forbidden.
	Path SecretPath `form:"path" json:"path"`
}

// GetSecretsParams defines parameters for GetSecrets.
type GetSecretsParams struct {
	// Path Slash-delimited secret path. Empty, `.`, and `..` segments are forbidden.
	Path *string `form:"path,omitempty" json:"path,omitempty"`

	// Prefix Slash-delimited prefix used to list secret metadata. One optional trailing slash is allowed; empty interior, `.`, and `..` segments are forbidden.
	Prefix *SecretPrefix `form:"prefix,omitempty" json:"prefix,omitempty"`
}

// GetSecrets200JSONResponseBody defines parameters for GetSecrets.
type GetSecrets200JSONResponseBody struct {
	union json.RawMessage
}

// PutSecretParams defines parameters for PutSecret.
type PutSecretParams struct {
	// Path Required slash-delimited item path; empty, `.`, and `..` segments are forbidden.
	Path SecretPath `form:"path" json:"path"`
}

// CreateTenantJSONRequestBody defines body for CreateTenant for application/json ContentType.
type CreateTenantJSONRequestBody = TenantCreate

// UpdateTenantJSONRequestBody defines body for UpdateTenant for application/json ContentType.
type UpdateTenantJSONRequestBody = TenantUpdate

// CreateVaultJSONRequestBody defines body for CreateVault for application/json ContentType.
type CreateVaultJSONRequestBody = VaultCreate

// UpdateVaultJSONRequestBody defines body for UpdateVault for application/json ContentType.
type UpdateVaultJSONRequestBody = VaultUpdate

// PutSecretJSONRequestBody defines body for PutSecret for application/json ContentType.
type PutSecretJSONRequestBody = SecretWrite

// AsSecret returns the union data inside the GetSecrets200JSONResponseBody as a Secret
func (t GetSecrets200JSONResponseBody) AsSecret() (Secret, error) {
	var body Secret
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSecret overwrites any union data inside the GetSecrets200JSONResponseBody as the provided Secret
func (t *GetSecrets200JSONResponseBody) FromSecret(v Secret) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSecret performs a merge with any union data inside the GetSecrets200JSONResponseBody, using the provided Secret
func (t *GetSecrets200JSONResponseBody) MergeSecret(v Secret) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSecretList returns the union data inside the GetSecrets200JSONResponseBody as a SecretList
func (t GetSecrets200JSONResponseBody) AsSecretList() (SecretList, error) {
	var body SecretList
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSecretList overwrites any union data inside the GetSecrets200JSONResponseBody as the provided SecretList
func (t *GetSecrets200JSONResponseBody) FromSecretList(v SecretList) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSecretList performs a merge with any union data inside the GetSecrets200JSONResponseBody, using the provided SecretList
func (t *GetSecrets200JSONResponseBody) MergeSecretList(v SecretList) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t GetSecrets200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *GetSecrets200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListTenants List tenants
	// (GET /api/v1/tenants)
	ListTenants(w http.ResponseWriter, r *http.Request)
	// CreateTenant Create a tenant
	// (POST /api/v1/tenants)
	CreateTenant(w http.ResponseWriter, r *http.Request)
	// DeleteTenant Delete a tenant
	// (DELETE /api/v1/tenants/{tenantId})
	DeleteTenant(w http.ResponseWriter, r *http.Request, tenantId TenantId)
	// GetTenant Get a tenant
	// (GET /api/v1/tenants/{tenantId})
	GetTenant(w http.ResponseWriter, r *http.Request, tenantId TenantId)
	// UpdateTenant Update a tenant
	// (PATCH /api/v1/tenants/{tenantId})
	UpdateTenant(w http.ResponseWriter, r *http.Request, tenantId TenantId)
	// ListVaults List vaults
	// (GET /api/v1/tenants/{tenantId}/vaults)
	ListVaults(w http.ResponseWriter, r *http.Request, tenantId TenantId)
	// CreateVault Create a vault
	// (POST /api/v1/tenants/{tenantId}/vaults)
	CreateVault(w http.ResponseWriter, r *http.Request, tenantId TenantId)
	// DeleteVault Delete a vault
	// (DELETE /api/v1/tenants/{tenantId}/vaults/{vaultId})
	DeleteVault(w http.ResponseWriter, r *http.Request, tenantId TenantId, vaultId VaultId)
	// GetVault Get a vault
	// (GET /api/v1/tenants/{tenantId}/vaults/{vaultId})
	GetVault(w http.ResponseWriter, r *http.Request, tenantId TenantId, vaultId VaultId)
	// UpdateVault Update a vault
	// (PATCH /api/v1/tenants/{tenantId}/vaults/{vaultId})
	UpdateVault(w http.ResponseWriter, r *http.Request, tenantId TenantId, vaultId VaultId)
	// DeleteSecret Delete a secret
	// (DELETE /api/v1/tenants/{tenantId}/vaults/{vaultId}/secrets)
	DeleteSecret(w http.ResponseWriter, r *http.Request, tenantId TenantId, vaultId VaultId, params DeleteSecretParams)
	// GetSecrets Get a secret or list secret metadata
	// (GET /api/v1/tenants/{tenantId}/vaults/{vaultId}/secrets)
	GetSecrets(w http.ResponseWriter, r *http.Request, tenantId TenantId, vaultId VaultId, params GetSecretsParams)
	// PutSecret Write a secret
	// (PUT /api/v1/tenants/{tenantId}/vaults/{vaultId}/secrets)
	PutSecret(w http.ResponseWriter, r *http.Request, tenantId TenantId, vaultId VaultId, params PutSecretParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListTenants operation middleware
func (siw *ServerInterfaceWrapper) ListTenants(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTenants(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTenant operation middleware
func (siw *ServerInterfaceWrapper) CreateTenant(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTenant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTenant operation middleware
func (siw *ServerInterfaceWrapper) DeleteTenant(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", r.PathValue("tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTenant(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTenant operation middleware
func (siw *ServerInterfaceWrapper) GetTenant(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", r.PathValue("tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTenant(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTenant operation middleware
func (siw *ServerInterfaceWrapper) UpdateTenant(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", r.PathValue("tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTenant(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVaults operation middleware
func (siw *ServerInterfaceWrapper) ListVaults(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", r.PathValue("tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVaults(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateVault operation middleware
func (siw *ServerInterfaceWrapper) CreateVault(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", r.PathValue("tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateVault(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVault operation middleware
func (siw *ServerInterfaceWrapper) DeleteVault(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", r.PathValue("tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	// ------------- Path parameter "vaultId" -------------
	var vaultId VaultId

	err = runtime.BindStyledParameterWithOptions("simple", "vaultId", r.PathValue("vaultId"), &vaultId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vaultId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVault(w, r, tenantId, vaultId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVault operation middleware
func (siw *ServerInterfaceWrapper) GetVault(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", r.PathValue("tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	// ------------- Path parameter "vaultId" -------------
	var vaultId VaultId

	err = runtime.BindStyledParameterWithOptions("simple", "vaultId", r.PathValue("vaultId"), &vaultId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vaultId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVault(w, r, tenantId, vaultId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateVault operation middleware
func (siw *ServerInterfaceWrapper) UpdateVault(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", r.PathValue("tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	// ------------- Path parameter "vaultId" -------------
	var vaultId VaultId

	err = runtime.BindStyledParameterWithOptions("simple", "vaultId", r.PathValue("vaultId"), &vaultId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vaultId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateVault(w, r, tenantId, vaultId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSecret operation middleware
func (siw *ServerInterfaceWrapper) DeleteSecret(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", r.PathValue("tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	// ------------- Path parameter "vaultId" -------------
	var vaultId VaultId

	err = runtime.BindStyledParameterWithOptions("simple", "vaultId", r.PathValue("vaultId"), &vaultId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vaultId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteSecretParams

	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "path", r.URL.Query(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSecret(w, r, tenantId, vaultId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSecrets operation middleware
func (siw *ServerInterfaceWrapper) GetSecrets(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", r.PathValue("tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	// ------------- Path parameter "vaultId" -------------
	var vaultId VaultId

	err = runtime.BindStyledParameterWithOptions("simple", "vaultId", r.PathValue("vaultId"), &vaultId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vaultId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSecretsParams

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "path", r.URL.Query(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "prefix" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "prefix", r.URL.Query(), &params.Prefix, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "prefix"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "prefix", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSecrets(w, r, tenantId, vaultId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutSecret operation middleware
func (siw *ServerInterfaceWrapper) PutSecret(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", r.PathValue("tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	// ------------- Path parameter "vaultId" -------------
	var vaultId VaultId

	err = runtime.BindStyledParameterWithOptions("simple", "vaultId", r.PathValue("vaultId"), &vaultId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vaultId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PutSecretParams

	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "path", r.URL.Query(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutSecret(w, r, tenantId, vaultId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/tenants", wrapper.ListTenants)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/tenants", wrapper.CreateTenant)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/tenants/{tenantId}", wrapper.DeleteTenant)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/tenants/{tenantId}", wrapper.GetTenant)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/tenants/{tenantId}", wrapper.UpdateTenant)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/tenants/{tenantId}/vaults", wrapper.ListVaults)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/tenants/{tenantId}/vaults", wrapper.CreateVault)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/tenants/{tenantId}/vaults/{vaultId}", wrapper.DeleteVault)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/tenants/{tenantId}/vaults/{vaultId}", wrapper.GetVault)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/tenants/{tenantId}/vaults/{vaultId}", wrapper.UpdateVault)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/tenants/{tenantId}/vaults/{vaultId}/secrets", wrapper.DeleteSecret)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/tenants/{tenantId}/vaults/{vaultId}/secrets", wrapper.GetSecrets)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/v1/tenants/{tenantId}/vaults/{vaultId}/secrets", wrapper.PutSecret)

	return m
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ConflictApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type InternalErrorApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type ListTenantsRequestObject struct {
}

type ListTenantsResponseObject interface {
	VisitListTenantsResponse(w http.ResponseWriter) error
}

type ListTenants200JSONResponse []Tenant

func (response ListTenants200JSONResponse) VisitListTenantsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTenants401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListTenants401ApplicationProblemPlusJSONResponse) VisitListTenantsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListTenants403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response ListTenants403ApplicationProblemPlusJSONResponse) VisitListTenantsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListTenants500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response ListTenants500ApplicationProblemPlusJSONResponse) VisitListTenantsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTenantRequestObject struct {
	Body *CreateTenantJSONRequestBody
}

type CreateTenantResponseObject interface {
	VisitCreateTenantResponse(w http.ResponseWriter) error
}

type CreateTenant201JSONResponse Tenant

func (response CreateTenant201JSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTenant400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateTenant400ApplicationProblemPlusJSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTenant401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response CreateTenant401ApplicationProblemPlusJSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTenant403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response CreateTenant403ApplicationProblemPlusJSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTenant409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response CreateTenant409ApplicationProblemPlusJSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTenant500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response CreateTenant500ApplicationProblemPlusJSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTenantRequestObject struct {
	TenantId TenantId `json:"tenantId"`
}

type DeleteTenantResponseObject interface {
	VisitDeleteTenantResponse(w http.ResponseWriter) error
}

type DeleteTenant204Response struct {
}

func (response DeleteTenant204Response) VisitDeleteTenantResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTenant400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response DeleteTenant400ApplicationProblemPlusJSONResponse) VisitDeleteTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTenant401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response DeleteTenant401ApplicationProblemPlusJSONResponse) VisitDeleteTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTenant403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response DeleteTenant403ApplicationProblemPlusJSONResponse) VisitDeleteTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTenant404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response DeleteTenant404ApplicationProblemPlusJSONResponse) VisitDeleteTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTenant409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response DeleteTenant409ApplicationProblemPlusJSONResponse) VisitDeleteTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTenant500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response DeleteTenant500ApplicationProblemPlusJSONResponse) VisitDeleteTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetTenantRequestObject struct {
	TenantId TenantId `json:"tenantId"`
}

type GetTenantResponseObject interface {
	VisitGetTenantResponse(w http.ResponseWriter) error
}

type GetTenant200JSONResponse Tenant

func (response GetTenant200JSONResponse) VisitGetTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTenant400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetTenant400ApplicationProblemPlusJSONResponse) VisitGetTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetTenant401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetTenant401ApplicationProblemPlusJSONResponse) VisitGetTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetTenant403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response GetTenant403ApplicationProblemPlusJSONResponse) VisitGetTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetTenant404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetTenant404ApplicationProblemPlusJSONResponse) VisitGetTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetTenant500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetTenant500ApplicationProblemPlusJSONResponse) VisitGetTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTenantRequestObject struct {
	TenantId TenantId `json:"tenantId"`
	Body     *UpdateTenantJSONRequestBody
}

type UpdateTenantResponseObject interface {
	VisitUpdateTenantResponse(w http.ResponseWriter) error
}

type UpdateTenant200JSONResponse Tenant

func (response UpdateTenant200JSONResponse) VisitUpdateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTenant400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response UpdateTenant400ApplicationProblemPlusJSONResponse) VisitUpdateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTenant401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response UpdateTenant401ApplicationProblemPlusJSONResponse) VisitUpdateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTenant403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response UpdateTenant403ApplicationProblemPlusJSONResponse) VisitUpdateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTenant404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response UpdateTenant404ApplicationProblemPlusJSONResponse) VisitUpdateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTenant409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response UpdateTenant409ApplicationProblemPlusJSONResponse) VisitUpdateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTenant500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response UpdateTenant500ApplicationProblemPlusJSONResponse) VisitUpdateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListVaultsRequestObject struct {
	TenantId TenantId `json:"tenantId"`
}

type ListVaultsResponseObject interface {
	VisitListVaultsResponse(w http.ResponseWriter) error
}

type ListVaults200JSONResponse []Vault

func (response ListVaults200JSONResponse) VisitListVaultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListVaults400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ListVaults400ApplicationProblemPlusJSONResponse) VisitListVaultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListVaults401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListVaults401ApplicationProblemPlusJSONResponse) VisitListVaultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListVaults403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response ListVaults403ApplicationProblemPlusJSONResponse) VisitListVaultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListVaults404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response ListVaults404ApplicationProblemPlusJSONResponse) VisitListVaultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListVaults500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response ListVaults500ApplicationProblemPlusJSONResponse) VisitListVaultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateVaultRequestObject struct {
	TenantId TenantId `json:"tenantId"`
	Body     *CreateVaultJSONRequestBody
}

type CreateVaultResponseObject interface {
	VisitCreateVaultResponse(w http.ResponseWriter) error
}

type CreateVault201JSONResponse Vault

func (response CreateVault201JSONResponse) VisitCreateVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateVault400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateVault400ApplicationProblemPlusJSONResponse) VisitCreateVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateVault401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response CreateVault401ApplicationProblemPlusJSONResponse) VisitCreateVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateVault403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response CreateVault403ApplicationProblemPlusJSONResponse) VisitCreateVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateVault404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response CreateVault404ApplicationProblemPlusJSONResponse) VisitCreateVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateVault409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response CreateVault409ApplicationProblemPlusJSONResponse) VisitCreateVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateVault500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response CreateVault500ApplicationProblemPlusJSONResponse) VisitCreateVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteVaultRequestObject struct {
	TenantId TenantId `json:"tenantId"`
	VaultId  VaultId  `json:"vaultId"`
}

type DeleteVaultResponseObject interface {
	VisitDeleteVaultResponse(w http.ResponseWriter) error
}

type DeleteVault204Response struct {
}

func (response DeleteVault204Response) VisitDeleteVaultResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteVault400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response DeleteVault400ApplicationProblemPlusJSONResponse) VisitDeleteVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteVault401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response DeleteVault401ApplicationProblemPlusJSONResponse) VisitDeleteVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteVault403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response DeleteVault403ApplicationProblemPlusJSONResponse) VisitDeleteVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteVault404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response DeleteVault404ApplicationProblemPlusJSONResponse) VisitDeleteVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteVault409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response DeleteVault409ApplicationProblemPlusJSONResponse) VisitDeleteVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteVault500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response DeleteVault500ApplicationProblemPlusJSONResponse) VisitDeleteVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetVaultRequestObject struct {
	TenantId TenantId `json:"tenantId"`
	VaultId  VaultId  `json:"vaultId"`
}

type GetVaultResponseObject interface {
	VisitGetVaultResponse(w http.ResponseWriter) error
}

type GetVault200JSONResponse Vault

func (response GetVault200JSONResponse) VisitGetVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVault400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetVault400ApplicationProblemPlusJSONResponse) VisitGetVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetVault401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetVault401ApplicationProblemPlusJSONResponse) VisitGetVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetVault403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response GetVault403ApplicationProblemPlusJSONResponse) VisitGetVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetVault404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetVault404ApplicationProblemPlusJSONResponse) VisitGetVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetVault500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetVault500ApplicationProblemPlusJSONResponse) VisitGetVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateVaultRequestObject struct {
	TenantId TenantId `json:"tenantId"`
	VaultId  VaultId  `json:"vaultId"`
	Body     *UpdateVaultJSONRequestBody
}

type UpdateVaultResponseObject interface {
	VisitUpdateVaultResponse(w http.ResponseWriter) error
}

type UpdateVault200JSONResponse Vault

func (response UpdateVault200JSONResponse) VisitUpdateVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateVault400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response UpdateVault400ApplicationProblemPlusJSONResponse) VisitUpdateVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateVault401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response UpdateVault401ApplicationProblemPlusJSONResponse) VisitUpdateVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateVault403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response UpdateVault403ApplicationProblemPlusJSONResponse) VisitUpdateVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateVault404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response UpdateVault404ApplicationProblemPlusJSONResponse) VisitUpdateVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateVault409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response UpdateVault409ApplicationProblemPlusJSONResponse) VisitUpdateVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateVault500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response UpdateVault500ApplicationProblemPlusJSONResponse) VisitUpdateVaultResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSecretRequestObject struct {
	TenantId TenantId `json:"tenantId"`
	VaultId  VaultId  `json:"vaultId"`
	Params   DeleteSecretParams
}

type DeleteSecretResponseObject interface {
	VisitDeleteSecretResponse(w http.ResponseWriter) error
}

type DeleteSecret204Response struct {
}

func (response DeleteSecret204Response) VisitDeleteSecretResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteSecret400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response DeleteSecret400ApplicationProblemPlusJSONResponse) VisitDeleteSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSecret401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response DeleteSecret401ApplicationProblemPlusJSONResponse) VisitDeleteSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSecret403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response DeleteSecret403ApplicationProblemPlusJSONResponse) VisitDeleteSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSecret404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response DeleteSecret404ApplicationProblemPlusJSONResponse) VisitDeleteSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSecret500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response DeleteSecret500ApplicationProblemPlusJSONResponse) VisitDeleteSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetSecretsRequestObject struct {
	TenantId TenantId `json:"tenantId"`
	VaultId  VaultId  `json:"vaultId"`
	Params   GetSecretsParams
}

type GetSecretsResponseObject interface {
	VisitGetSecretsResponse(w http.ResponseWriter) error
}

type GetSecrets200JSONResponse = GetSecrets200JSONResponseBody

func (response GetSecrets200JSONResponse) VisitGetSecretsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.union); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSecrets400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetSecrets400ApplicationProblemPlusJSONResponse) VisitGetSecretsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetSecrets401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetSecrets401ApplicationProblemPlusJSONResponse) VisitGetSecretsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetSecrets403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response GetSecrets403ApplicationProblemPlusJSONResponse) VisitGetSecretsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetSecrets404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetSecrets404ApplicationProblemPlusJSONResponse) VisitGetSecretsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetSecrets500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetSecrets500ApplicationProblemPlusJSONResponse) VisitGetSecretsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PutSecretRequestObject struct {
	TenantId TenantId `json:"tenantId"`
	VaultId  VaultId  `json:"vaultId"`
	Params   PutSecretParams
	Body     *PutSecretJSONRequestBody
}

type PutSecretResponseObject interface {
	VisitPutSecretResponse(w http.ResponseWriter) error
}

type PutSecret200JSONResponse Secret

func (response PutSecret200JSONResponse) VisitPutSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PutSecret400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response PutSecret400ApplicationProblemPlusJSONResponse) VisitPutSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutSecret401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response PutSecret401ApplicationProblemPlusJSONResponse) VisitPutSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PutSecret403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response PutSecret403ApplicationProblemPlusJSONResponse) VisitPutSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PutSecret404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response PutSecret404ApplicationProblemPlusJSONResponse) VisitPutSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PutSecret409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response PutSecret409ApplicationProblemPlusJSONResponse) VisitPutSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PutSecret500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response PutSecret500ApplicationProblemPlusJSONResponse) VisitPutSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListTenants List tenants
	// (GET /api/v1/tenants)
	ListTenants(ctx context.Context, request ListTenantsRequestObject) (ListTenantsResponseObject, error)
	// CreateTenant Create a tenant
	// (POST /api/v1/tenants)
	CreateTenant(ctx context.Context, request CreateTenantRequestObject) (CreateTenantResponseObject, error)
	// DeleteTenant Delete a tenant
	// (DELETE /api/v1/tenants/{tenantId})
	DeleteTenant(ctx context.Context, request DeleteTenantRequestObject) (DeleteTenantResponseObject, error)
	// GetTenant Get a tenant
	// (GET /api/v1/tenants/{tenantId})
	GetTenant(ctx context.Context, request GetTenantRequestObject) (GetTenantResponseObject, error)
	// UpdateTenant Update a tenant
	// (PATCH /api/v1/tenants/{tenantId})
	UpdateTenant(ctx context.Context, request UpdateTenantRequestObject) (UpdateTenantResponseObject, error)
	// ListVaults List vaults
	// (GET /api/v1/tenants/{tenantId}/vaults)
	ListVaults(ctx context.Context, request ListVaultsRequestObject) (ListVaultsResponseObject, error)
	// CreateVault Create a vault
	// (POST /api/v1/tenants/{tenantId}/vaults)
	CreateVault(ctx context.Context, request CreateVaultRequestObject) (CreateVaultResponseObject, error)
	// DeleteVault Delete a vault
	// (DELETE /api/v1/tenants/{tenantId}/vaults/{vaultId})
	DeleteVault(ctx context.Context, request DeleteVaultRequestObject) (DeleteVaultResponseObject, error)
	// GetVault Get a vault
	// (GET /api/v1/tenants/{tenantId}/vaults/{vaultId})
	GetVault(ctx context.Context, request GetVaultRequestObject) (GetVaultResponseObject, error)
	// UpdateVault Update a vault
	// (PATCH /api/v1/tenants/{tenantId}/vaults/{vaultId})
	UpdateVault(ctx context.Context, request UpdateVaultRequestObject) (UpdateVaultResponseObject, error)
	// DeleteSecret Delete a secret
	// (DELETE /api/v1/tenants/{tenantId}/vaults/{vaultId}/secrets)
	DeleteSecret(ctx context.Context, request DeleteSecretRequestObject) (DeleteSecretResponseObject, error)
	// GetSecrets Get a secret or list secret metadata
	// (GET /api/v1/tenants/{tenantId}/vaults/{vaultId}/secrets)
	GetSecrets(ctx context.Context, request GetSecretsRequestObject) (GetSecretsResponseObject, error)
	// PutSecret Write a secret
	// (PUT /api/v1/tenants/{tenantId}/vaults/{vaultId}/secrets)
	PutSecret(ctx context.Context, request PutSecretRequestObject) (PutSecretResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListTenants operation middleware
func (sh *strictHandler) ListTenants(w http.ResponseWriter, r *http.Request) {
	var request ListTenantsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTenants(ctx, request.(ListTenantsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTenants")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTenantsResponseObject); ok {
		if err := validResponse.VisitListTenantsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTenant operation middleware
func (sh *strictHandler) CreateTenant(w http.ResponseWriter, r *http.Request) {
	var request CreateTenantRequestObject

	var body CreateTenantJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTenant(ctx, request.(CreateTenantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTenant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTenantResponseObject); ok {
		if err := validResponse.VisitCreateTenantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTenant operation middleware
func (sh *strictHandler) DeleteTenant(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	var request DeleteTenantRequestObject

	request.TenantId = tenantId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTenant(ctx, request.(DeleteTenantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTenant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTenantResponseObject); ok {
		if err := validResponse.VisitDeleteTenantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTenant operation middleware
func (sh *strictHandler) GetTenant(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	var request GetTenantRequestObject

	request.TenantId = tenantId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTenant(ctx, request.(GetTenantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTenant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTenantResponseObject); ok {
		if err := validResponse.VisitGetTenantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTenant operation middleware
func (sh *strictHandler) UpdateTenant(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	var request UpdateTenantRequestObject

	request.TenantId = tenantId

	var body UpdateTenantJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTenant(ctx, request.(UpdateTenantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTenant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTenantResponseObject); ok {
		if err := validResponse.VisitUpdateTenantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListVaults operation middleware
func (sh *strictHandler) ListVaults(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	var request ListVaultsRequestObject

	request.TenantId = tenantId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVaults(ctx, request.(ListVaultsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVaults")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVaultsResponseObject); ok {
		if err := validResponse.VisitListVaultsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateVault operation middleware
func (sh *strictHandler) CreateVault(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	var request CreateVaultRequestObject

	request.TenantId = tenantId

	var body CreateVaultJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateVault(ctx, request.(CreateVaultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateVault")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateVaultResponseObject); ok {
		if err := validResponse.VisitCreateVaultResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteVault operation middleware
func (sh *strictHandler) DeleteVault(w http.ResponseWriter, r *http.Request, tenantId TenantId, vaultId VaultId) {
	var request DeleteVaultRequestObject

	request.TenantId = tenantId
	request.VaultId = vaultId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteVault(ctx, request.(DeleteVaultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteVault")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteVaultResponseObject); ok {
		if err := validResponse.VisitDeleteVaultResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVault operation middleware
func (sh *strictHandler) GetVault(w http.ResponseWriter, r *http.Request, tenantId TenantId, vaultId VaultId) {
	var request GetVaultRequestObject

	request.TenantId = tenantId
	request.VaultId = vaultId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVault(ctx, request.(GetVaultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVault")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVaultResponseObject); ok {
		if err := validResponse.VisitGetVaultResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateVault operation middleware
func (sh *strictHandler) UpdateVault(w http.ResponseWriter, r *http.Request, tenantId TenantId, vaultId VaultId) {
	var request UpdateVaultRequestObject

	request.TenantId = tenantId
	request.VaultId = vaultId

	var body UpdateVaultJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateVault(ctx, request.(UpdateVaultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateVault")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateVaultResponseObject); ok {
		if err := validResponse.VisitUpdateVaultResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSecret operation middleware
func (sh *strictHandler) DeleteSecret(w http.ResponseWriter, r *http.Request, tenantId TenantId, vaultId VaultId, params DeleteSecretParams) {
	var request DeleteSecretRequestObject

	request.TenantId = tenantId
	request.VaultId = vaultId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSecret(ctx, request.(DeleteSecretRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSecret")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSecretResponseObject); ok {
		if err := validResponse.VisitDeleteSecretResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSecrets operation middleware
func (sh *strictHandler) GetSecrets(w http.ResponseWriter, r *http.Request, tenantId TenantId, vaultId VaultId, params GetSecretsParams) {
	var request GetSecretsRequestObject

	request.TenantId = tenantId
	request.VaultId = vaultId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSecrets(ctx, request.(GetSecretsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSecrets")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSecretsResponseObject); ok {
		if err := validResponse.VisitGetSecretsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutSecret operation middleware
func (sh *strictHandler) PutSecret(w http.ResponseWriter, r *http.Request, tenantId TenantId, vaultId VaultId, params PutSecretParams) {
	var request PutSecretRequestObject

	request.TenantId = tenantId
	request.VaultId = vaultId
	request.Params = params

	var body PutSecretJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutSecret(ctx, request.(PutSecretRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutSecret")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutSecretResponseObject); ok {
		if err := validResponse.VisitPutSecretResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
