//go:build go1.22

// Package internalapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package internalapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AuditEventOutcome.
const (
	Failure AuditEventOutcome = "failure"
	Success AuditEventOutcome = "success"
)

// Valid indicates whether the value is a known member of the AuditEventOutcome enum.
func (e AuditEventOutcome) Valid() bool {
	switch e {
	case Failure:
		return true
	case Success:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	Ok HealthStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for UnavailableStatusStatus.
const (
	Unavailable UnavailableStatusStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the UnavailableStatusStatus enum.
func (e UnavailableStatusStatus) Valid() bool {
	switch e {
	case Unavailable:
		return true
	default:
		return false
	}
}

// AuditEvent Request audit metadata without request bodies, query strings, credentials, or plaintext secret paths.
type AuditEvent struct {
	// Method Example: GET
	Method string `json:"method"`

	// OccurredAt Example: 2026-08-29T15:04:05Z
	OccurredAt time.Time `json:"occurredAt"`

	// Outcome Example: success
	Outcome AuditEventOutcome `json:"outcome"`

	// PrincipalId Authenticated principal identifier; absent when authentication did not succeed.
	//
	// Example: operator
	PrincipalId *string `json:"principalId,omitempty"`

	// RequestId Example: 11111111-1111-4111-8111-111111111111
	RequestId string `json:"requestId"`

	// Route Request path without its query string.
	//
	// Example: /api/v1/tenants/11111111-1111-4111-8111-111111111111
	Route string `json:"route"`

	// SecretPathSha256 Keyed HMAC-SHA-256 digest of the decoded logical secret path or list prefix; the plaintext is never persisted and the deployment key is never returned.
	//
	// Example: 2bb80d537b1da3e38bd30361aa855686bde0ba53e611d8a8a5e47993629e366f
	SecretPathSha256 *string `json:"secretPathSha256,omitempty"`

	// Sequence Example: 42
	Sequence int64 `json:"sequence"`

	// StatusCode Example: 200
	StatusCode int32 `json:"statusCode"`
}

// AuditEventOutcome Example: success
type AuditEventOutcome string

// AuditEventList Ordered page from the append-only audit ledger.
type AuditEventList struct {
	// HasMore Whether another event exists after the last returned sequence.
	//
	// Example: false
	HasMore bool `json:"hasMore"`

	// Items Example: [{"method":"GET","occurredAt":"2026-08-29T15:04:05Z","outcome":"success","principalId":"operator","requestId":"11111111-1111-4111-8111-111111111111","route":"/api/v1/tenants/11111111-1111-4111-8111-111111111111","sequence":42,"statusCode":200}]
	Items []AuditEvent `json:"items"`

	// NextAfterSequence Exclusive checkpoint for the next page; null when hasMore is false.
	NextAfterSequence *int64 `json:"nextAfterSequence"`
}

// AuthorizationPolicy Allow policy for a role or principal, domain, path pattern, and HTTP method. Secret operation policies may additionally narrow access to a literal logical secret path prefix.
type AuthorizationPolicy struct {
	// Domain Example: 11111111-1111-4111-8111-111111111111
	Domain string `json:"domain"`

	// Method Example: GET
	Method string `json:"method"`

	// Path Example: /api/v1/tenants/{tenantId}/vaults/{vaultId}/secret
	Path string `json:"path"`

	// SecretPathPrefix Literal logical secret path prefix. Only valid when path is the secret item, secret metadata, or secret collection route; the decoded path/prefix query value must begin with this prefix. An empty collection prefix is not authorized for a path-scoped policy. The reserved value '*' preserves legacy vault-wide behavior.
	//
	// Example: prod/database/
	SecretPathPrefix *string `json:"secretPathPrefix,omitempty"`

	// Subject Example: secret-reader
	Subject string `json:"subject"`
}

// AuthorizationRoleBinding Principal-to-role binding scoped to one authorization domain.
type AuthorizationRoleBinding struct {
	// Domain Example: 11111111-1111-4111-8111-111111111111
	Domain string `json:"domain"`

	// Principal Example: controller
	Principal string `json:"principal"`

	// Role Example: secret-reader
	Role string `json:"role"`
}

// AuthorizationSnapshot Persisted authorization state; token digests are intentionally omitted.
type AuthorizationSnapshot struct {
	// Initialized Example: true
	Initialized bool `json:"initialized"`

	// Policies Example: [{"domain":"tenant-a","method":"GET","path":"/api/v1/tenants/{tenantId}/vaults/{vaultId}/secret","subject":"secret-reader"}]
	Policies []AuthorizationPolicy `json:"policies"`

	// Revision Monotonic snapshot revision used by ETag and optimistic concurrency.
	//
	// Example: 3
	Revision int64 `json:"revision"`

	// RoleBindings Example: [{"domain":"tenant-a","principal":"controller","role":"secret-reader"}]
	RoleBindings []AuthorizationRoleBinding `json:"roleBindings"`
}

// AuthorizationSnapshotInput Complete replacement snapshot; empty arrays intentionally mean default-deny.
type AuthorizationSnapshotInput struct {
	// Policies Example: [{"domain":"tenant-a","method":"GET","path":"/api/v1/tenants/{tenantId}/vaults/{vaultId}/secret","subject":"secret-reader"}]
	Policies []AuthorizationPolicy `json:"policies"`

	// RoleBindings Example: [{"domain":"tenant-a","principal":"controller","role":"secret-reader"}]
	RoleBindings []AuthorizationRoleBinding `json:"roleBindings"`
}

// EncryptionRotationResult Bounded root-key rewrap result. It contains counts and a keyset checkpoint only; no key material or secret data is returned.
type EncryptionRotationResult struct {
	// ActiveRootKeyEpoch Monotonic deployment epoch that fences stale server processes during rollout.
	//
	// Example: 2
	ActiveRootKeyEpoch int64 `json:"activeRootKeyEpoch"`

	// ActiveRootKeyId Identifier of the deployment key era used for new and rewrapped vault keys.
	//
	// Example: root-v2
	ActiveRootKeyId string `json:"activeRootKeyId"`

	// Complete True when no vault key currently uses an older root-key era. A fresh full sweep should be run after transient failures or concurrent maintenance.
	//
	// Example: false
	Complete bool `json:"complete"`

	// HasMore Example: true
	HasMore bool `json:"hasMore"`

	// NextAfterTenantId Checkpoint for the next page; null when hasMore is false.
	//
	// Example: 11111111-1111-4111-8111-111111111111
	NextAfterTenantId *string `json:"nextAfterTenantId"`

	// NextAfterVaultId Checkpoint for the next page; null when hasMore is false.
	//
	// Example: 22222222-2222-4222-8222-222222222222
	NextAfterVaultId *string `json:"nextAfterVaultId"`

	// RemainingOldKeys Current count of vault keys whose root key ID differs from the active era; this is not a snapshot.
	//
	// Example: 3
	RemainingOldKeys int64 `json:"remainingOldKeys"`

	// Rewrapped Example: 47
	Rewrapped int32 `json:"rewrapped"`

	// Scanned Example: 50
	Scanned int32 `json:"scanned"`

	// Skipped Keys already using the active era or changed by another worker before this request committed.
	//
	// Example: 3
	Skipped int32 `json:"skipped"`
}

// HealthStatus Minimal probe result with no deployment details.
type HealthStatus struct {
	// Status Example: ok
	Status HealthStatusStatus `json:"status"`
}

// HealthStatusStatus Example: ok
type HealthStatusStatus string

// Problem Problem Details response compatible with RFC 9457.
type Problem struct {
	// Code Stable machine-readable error code. Implementations currently use
	// unauthorized, forbidden, invalid_request, invalid_json,
	// invalid_content_type, invalid_request_id, validation_failed,
	// invalid_if_match, invalid_if_none_match, invalid_cursor, cursor_expired,
	// invalid_resource_version, invalid_watch_timeout, resource_version_ahead,
	// resource_not_found,
	// resource_conflict, resource_has_children, idempotency_key_conflict,
	// etag_mismatch, secret_too_large, invalid_rotation_checkpoint,
	// invalid_limit, encryption_key_epoch_conflict, service_unavailable,
	// and internal_error.
	//
	//
	// Example: resource_not_found
	Code string `json:"code"`

	// Detail Human-readable detail that never contains secret values.
	//
	// Example: The requested resource does not exist.
	Detail *string `json:"detail,omitempty"`

	// Errors Example: [{"code":"invalid_format","field":"/name","message":"must match the documented name format"}]
	Errors *[]ProblemError `json:"errors,omitempty"`

	// Instance Occurrence identifier for support correlation.
	//
	// Example: urn:moco:request:11111111-1111-4111-8111-111111111111
	Instance *string `json:"instance,omitempty"`

	// RequestId Correlation identifier also returned in X-Request-ID.
	//
	// Example: 11111111-1111-4111-8111-111111111111
	RequestId string `json:"requestId"`

	// ResourceId Existing resource ID when safely useful for conflict recovery.
	//
	// Example: 11111111-1111-4111-8111-111111111111
	ResourceId *string `json:"resourceId,omitempty"`

	// Status Example: 404
	Status int32 `json:"status"`

	// Title Example: Not Found
	Title string `json:"title"`

	// Type Stable documentation URI for this problem type.
	//
	// Example: https://moco.araihu.com/problems/not-found
	Type string `json:"type"`
}

// ProblemError Field-specific validation failure safe to expose to clients.
type ProblemError struct {
	// Code Stable machine-readable validation code.
	//
	// Example: invalid_format
	Code *string `json:"code,omitempty"`

	// Field JSON Pointer or parameter name when the failure has a location.
	//
	// Example: /name
	Field *string `json:"field,omitempty"`

	// Message Human-readable message that never contains secret values.
	//
	// Example: must match the documented name format
	Message string `json:"message"`
}

// UnavailableStatus Minimal readiness failure with no dependency details.
type UnavailableStatus struct {
	// Status Example: unavailable
	Status UnavailableStatusStatus `json:"status"`
}

// UnavailableStatusStatus Example: unavailable
type UnavailableStatusStatus string

// AuditAfterSequence Example: 42
type AuditAfterSequence = int64

// EncryptionAfterTenantId defines model for encryption-after-tenant-id.
type EncryptionAfterTenantId = string

// EncryptionAfterVaultId defines model for encryption-after-vault-id.
type EncryptionAfterVaultId = string

// Limit defines model for limit.
type Limit = int32

// RequestId defines model for request-id.
type RequestId = string

// BadRequest Problem Details response compatible with RFC 9457.
type BadRequest = Problem

// Conflict Problem Details response compatible with RFC 9457.
type Conflict = Problem

// Forbidden Problem Details response compatible with RFC 9457.
type Forbidden = Problem

// InternalError Problem Details response compatible with RFC 9457.
type InternalError = Problem

// PreconditionFailed Problem Details response compatible with RFC 9457.
type PreconditionFailed = Problem

// ServiceUnavailable Problem Details response compatible with RFC 9457.
type ServiceUnavailable = Problem

// Unauthorized Problem Details response compatible with RFC 9457.
type Unauthorized = Problem

// ListAuditEventsParams defines parameters for ListAuditEvents.
type ListAuditEventsParams struct {
	// AfterSequence Exclusive audit sequence checkpoint. Use the returned nextAfterSequence to continue the same ordered ledger page.
	AfterSequence *AuditAfterSequence `form:"afterSequence,omitempty" json:"afterSequence,omitempty"`

	// Limit Maximum number of items to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// XRequestID Optional caller correlation ID; the server returns the effective ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// GetAuthorizationSnapshotParams defines parameters for GetAuthorizationSnapshot.
type GetAuthorizationSnapshotParams struct {
	// XRequestID Optional caller correlation ID; the server returns the effective ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// ReplaceAuthorizationSnapshotParams defines parameters for ReplaceAuthorizationSnapshot.
type ReplaceAuthorizationSnapshotParams struct {
	// IfMatch Strong ETag returned by the latest GET or PUT response. Use `*` to apply against the revision observed immediately before this request.
	IfMatch string `json:"If-Match"`

	// XRequestID Optional caller correlation ID; the server returns the effective ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// RotateEncryptionKeysParams defines parameters for RotateEncryptionKeys.
type RotateEncryptionKeysParams struct {
	// AfterTenantId Exclusive tenant identifier checkpoint returned with the preceding rotation page. Supply it together with afterVaultId.
	AfterTenantId *EncryptionAfterTenantId `form:"afterTenantId,omitempty" json:"afterTenantId,omitempty"`

	// AfterVaultId Exclusive vault identifier checkpoint returned with the preceding rotation page. Supply it together with afterTenantId.
	AfterVaultId *EncryptionAfterVaultId `form:"afterVaultId,omitempty" json:"afterVaultId,omitempty"`

	// Limit Maximum number of items to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// XRequestID Optional caller correlation ID; the server returns the effective ID.
	XRequestID *RequestId `json:"X-Request-ID,omitempty"`
}

// ReplaceAuthorizationSnapshotJSONRequestBody defines body for ReplaceAuthorizationSnapshot for application/json ContentType.
type ReplaceAuthorizationSnapshotJSONRequestBody = AuthorizationSnapshotInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListAuditEvents List request audit events
	// (GET /internal/v1/audit)
	ListAuditEvents(w http.ResponseWriter, r *http.Request, params ListAuditEventsParams)
	// GetAuthorizationSnapshot Read the persisted authorization snapshot
	// (GET /internal/v1/authorization)
	GetAuthorizationSnapshot(w http.ResponseWriter, r *http.Request, params GetAuthorizationSnapshotParams)
	// ReplaceAuthorizationSnapshot Replace the persisted authorization snapshot
	// (PUT /internal/v1/authorization)
	ReplaceAuthorizationSnapshot(w http.ResponseWriter, r *http.Request, params ReplaceAuthorizationSnapshotParams)
	// RotateEncryptionKeys Rewrap one bounded page of vault data keys
	// (POST /internal/v1/encryption/rotation)
	RotateEncryptionKeys(w http.ResponseWriter, r *http.Request, params RotateEncryptionKeysParams)
	// GetLiveness Check process liveness
	// (GET /livez)
	GetLiveness(w http.ResponseWriter, r *http.Request)
	// GetReadiness Check traffic readiness
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAuditEvents operation middleware
func (siw *ServerInterfaceWrapper) ListAuditEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAuditEventsParams

	// ------------- Optional query parameter "afterSequence" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "afterSequence", r.URL.Query(), &params.AfterSequence, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "afterSequence"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "afterSequence", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAuditEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthorizationSnapshot operation middleware
func (siw *ServerInterfaceWrapper) GetAuthorizationSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthorizationSnapshotParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthorizationSnapshot(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplaceAuthorizationSnapshot operation middleware
func (siw *ServerInterfaceWrapper) ReplaceAuthorizationSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ReplaceAuthorizationSnapshotParams

	headers := r.Header

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplaceAuthorizationSnapshot(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RotateEncryptionKeys operation middleware
func (siw *ServerInterfaceWrapper) RotateEncryptionKeys(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RotateEncryptionKeysParams

	// ------------- Optional query parameter "afterTenantId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "afterTenantId", r.URL.Query(), &params.AfterTenantId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "afterTenantId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "afterTenantId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "afterVaultId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "afterVaultId", r.URL.Query(), &params.AfterVaultId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "afterVaultId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "afterVaultId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID RequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RotateEncryptionKeys(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/livez", wrapper.GetLiveness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.GetReadiness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/internal/v1/authorization", wrapper.GetAuthorizationSnapshot)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/internal/v1/authorization", wrapper.ReplaceAuthorizationSnapshot)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/internal/v1/audit", wrapper.ListAuditEvents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/internal/v1/encryption/rotation", wrapper.RotateEncryptionKeys)

	return m
}

type BadRequestResponseHeaders struct {
	XRequestID string
}
type BadRequestApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers BadRequestResponseHeaders
}

type ConflictResponseHeaders struct {
	XRequestID string
}
type ConflictApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ConflictResponseHeaders
}

type ForbiddenResponseHeaders struct {
	XRequestID string
}
type ForbiddenApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ForbiddenResponseHeaders
}

type InternalErrorResponseHeaders struct {
	XRequestID string
}
type InternalErrorApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers InternalErrorResponseHeaders
}

type PreconditionFailedResponseHeaders struct {
	ETag       string
	XRequestID string
}
type PreconditionFailedApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers PreconditionFailedResponseHeaders
}

type ServiceUnavailableResponseHeaders struct {
	RetryAfter int32
	XRequestID string
}
type ServiceUnavailableApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ServiceUnavailableResponseHeaders
}

type UnauthorizedResponseHeaders struct {
	WWWAuthenticate string
	XRequestID      string
}
type UnauthorizedApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers UnauthorizedResponseHeaders
}

type ListAuditEventsRequestObject struct {
	Params ListAuditEventsParams
}

type ListAuditEventsResponseObject interface {
	VisitListAuditEventsResponse(w http.ResponseWriter) error
}

type ListAuditEvents200ResponseHeaders struct {
	XRequestID string
}

type ListAuditEvents200JSONResponse struct {
	Body    AuditEventList
	Headers ListAuditEvents200ResponseHeaders
}

func (response ListAuditEvents200JSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditEvents400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ListAuditEvents400ApplicationProblemPlusJSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditEvents401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListAuditEvents401ApplicationProblemPlusJSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditEvents403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response ListAuditEvents403ApplicationProblemPlusJSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditEvents500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response ListAuditEvents500ApplicationProblemPlusJSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuditEvents503ApplicationProblemPlusJSONResponse struct {
	ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response ListAuditEvents503ApplicationProblemPlusJSONResponse) VisitListAuditEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthorizationSnapshotRequestObject struct {
	Params GetAuthorizationSnapshotParams
}

type GetAuthorizationSnapshotResponseObject interface {
	VisitGetAuthorizationSnapshotResponse(w http.ResponseWriter) error
}

type GetAuthorizationSnapshot200ResponseHeaders struct {
	ETag       string
	XRequestID string
}

type GetAuthorizationSnapshot200JSONResponse struct {
	Body    AuthorizationSnapshot
	Headers GetAuthorizationSnapshot200ResponseHeaders
}

func (response GetAuthorizationSnapshot200JSONResponse) VisitGetAuthorizationSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthorizationSnapshot401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetAuthorizationSnapshot401ApplicationProblemPlusJSONResponse) VisitGetAuthorizationSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthorizationSnapshot403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response GetAuthorizationSnapshot403ApplicationProblemPlusJSONResponse) VisitGetAuthorizationSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthorizationSnapshot500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetAuthorizationSnapshot500ApplicationProblemPlusJSONResponse) VisitGetAuthorizationSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthorizationSnapshot503ApplicationProblemPlusJSONResponse struct {
	ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response GetAuthorizationSnapshot503ApplicationProblemPlusJSONResponse) VisitGetAuthorizationSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ReplaceAuthorizationSnapshotRequestObject struct {
	Params ReplaceAuthorizationSnapshotParams
	Body   *ReplaceAuthorizationSnapshotJSONRequestBody
}

type ReplaceAuthorizationSnapshotResponseObject interface {
	VisitReplaceAuthorizationSnapshotResponse(w http.ResponseWriter) error
}

type ReplaceAuthorizationSnapshot200ResponseHeaders struct {
	ETag       string
	XRequestID string
}

type ReplaceAuthorizationSnapshot200JSONResponse struct {
	Body    AuthorizationSnapshot
	Headers ReplaceAuthorizationSnapshot200ResponseHeaders
}

func (response ReplaceAuthorizationSnapshot200JSONResponse) VisitReplaceAuthorizationSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ReplaceAuthorizationSnapshot400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ReplaceAuthorizationSnapshot400ApplicationProblemPlusJSONResponse) VisitReplaceAuthorizationSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ReplaceAuthorizationSnapshot401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ReplaceAuthorizationSnapshot401ApplicationProblemPlusJSONResponse) VisitReplaceAuthorizationSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ReplaceAuthorizationSnapshot403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response ReplaceAuthorizationSnapshot403ApplicationProblemPlusJSONResponse) VisitReplaceAuthorizationSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ReplaceAuthorizationSnapshot412ApplicationProblemPlusJSONResponse struct {
	PreconditionFailedApplicationProblemPlusJSONResponse
}

func (response ReplaceAuthorizationSnapshot412ApplicationProblemPlusJSONResponse) VisitReplaceAuthorizationSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("ETag", fmt.Sprint(response.Headers.ETag))
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(412)
	_, err := buf.WriteTo(w)
	return err
}

type ReplaceAuthorizationSnapshot500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response ReplaceAuthorizationSnapshot500ApplicationProblemPlusJSONResponse) VisitReplaceAuthorizationSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ReplaceAuthorizationSnapshot503ApplicationProblemPlusJSONResponse struct {
	ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response ReplaceAuthorizationSnapshot503ApplicationProblemPlusJSONResponse) VisitReplaceAuthorizationSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type RotateEncryptionKeysRequestObject struct {
	Params RotateEncryptionKeysParams
}

type RotateEncryptionKeysResponseObject interface {
	VisitRotateEncryptionKeysResponse(w http.ResponseWriter) error
}

type RotateEncryptionKeys200ResponseHeaders struct {
	XRequestID string
}

type RotateEncryptionKeys200JSONResponse struct {
	Body    EncryptionRotationResult
	Headers RotateEncryptionKeys200ResponseHeaders
}

func (response RotateEncryptionKeys200JSONResponse) VisitRotateEncryptionKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RotateEncryptionKeys400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response RotateEncryptionKeys400ApplicationProblemPlusJSONResponse) VisitRotateEncryptionKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RotateEncryptionKeys401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response RotateEncryptionKeys401ApplicationProblemPlusJSONResponse) VisitRotateEncryptionKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RotateEncryptionKeys403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response RotateEncryptionKeys403ApplicationProblemPlusJSONResponse) VisitRotateEncryptionKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RotateEncryptionKeys409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response RotateEncryptionKeys409ApplicationProblemPlusJSONResponse) VisitRotateEncryptionKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RotateEncryptionKeys500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response RotateEncryptionKeys500ApplicationProblemPlusJSONResponse) VisitRotateEncryptionKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RotateEncryptionKeys503ApplicationProblemPlusJSONResponse struct {
	ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response RotateEncryptionKeys503ApplicationProblemPlusJSONResponse) VisitRotateEncryptionKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetLivenessRequestObject struct {
}

type GetLivenessResponseObject interface {
	VisitGetLivenessResponse(w http.ResponseWriter) error
}

type GetLiveness200JSONResponse HealthStatus

func (response GetLiveness200JSONResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200JSONResponse HealthStatus

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadiness503ResponseHeaders struct {
	RetryAfter int32
}

type GetReadiness503JSONResponse struct {
	Body    UnavailableStatus
	Headers GetReadiness503ResponseHeaders
}

func (response GetReadiness503JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListAuditEvents List request audit events
	// (GET /internal/v1/audit)
	ListAuditEvents(ctx context.Context, request ListAuditEventsRequestObject) (ListAuditEventsResponseObject, error)
	// GetAuthorizationSnapshot Read the persisted authorization snapshot
	// (GET /internal/v1/authorization)
	GetAuthorizationSnapshot(ctx context.Context, request GetAuthorizationSnapshotRequestObject) (GetAuthorizationSnapshotResponseObject, error)
	// ReplaceAuthorizationSnapshot Replace the persisted authorization snapshot
	// (PUT /internal/v1/authorization)
	ReplaceAuthorizationSnapshot(ctx context.Context, request ReplaceAuthorizationSnapshotRequestObject) (ReplaceAuthorizationSnapshotResponseObject, error)
	// RotateEncryptionKeys Rewrap one bounded page of vault data keys
	// (POST /internal/v1/encryption/rotation)
	RotateEncryptionKeys(ctx context.Context, request RotateEncryptionKeysRequestObject) (RotateEncryptionKeysResponseObject, error)
	// GetLiveness Check process liveness
	// (GET /livez)
	GetLiveness(ctx context.Context, request GetLivenessRequestObject) (GetLivenessResponseObject, error)
	// GetReadiness Check traffic readiness
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAuditEvents operation middleware
func (sh *strictHandler) ListAuditEvents(w http.ResponseWriter, r *http.Request, params ListAuditEventsParams) {
	var request ListAuditEventsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAuditEvents(ctx, request.(ListAuditEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAuditEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAuditEventsResponseObject); ok {
		if err := validResponse.VisitListAuditEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthorizationSnapshot operation middleware
func (sh *strictHandler) GetAuthorizationSnapshot(w http.ResponseWriter, r *http.Request, params GetAuthorizationSnapshotParams) {
	var request GetAuthorizationSnapshotRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthorizationSnapshot(ctx, request.(GetAuthorizationSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthorizationSnapshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthorizationSnapshotResponseObject); ok {
		if err := validResponse.VisitGetAuthorizationSnapshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReplaceAuthorizationSnapshot operation middleware
func (sh *strictHandler) ReplaceAuthorizationSnapshot(w http.ResponseWriter, r *http.Request, params ReplaceAuthorizationSnapshotParams) {
	var request ReplaceAuthorizationSnapshotRequestObject

	request.Params = params

	var body ReplaceAuthorizationSnapshotJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReplaceAuthorizationSnapshot(ctx, request.(ReplaceAuthorizationSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReplaceAuthorizationSnapshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReplaceAuthorizationSnapshotResponseObject); ok {
		if err := validResponse.VisitReplaceAuthorizationSnapshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RotateEncryptionKeys operation middleware
func (sh *strictHandler) RotateEncryptionKeys(w http.ResponseWriter, r *http.Request, params RotateEncryptionKeysParams) {
	var request RotateEncryptionKeysRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RotateEncryptionKeys(ctx, request.(RotateEncryptionKeysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RotateEncryptionKeys")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RotateEncryptionKeysResponseObject); ok {
		if err := validResponse.VisitRotateEncryptionKeysResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLiveness operation middleware
func (sh *strictHandler) GetLiveness(w http.ResponseWriter, r *http.Request) {
	var request GetLivenessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLiveness(ctx, request.(GetLivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLiveness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLivenessResponseObject); ok {
		if err := validResponse.VisitGetLivenessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
