// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"
	"database/sql"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_events (
    occurred_at,
    request_id,
    principal_id,
    method,
    route,
    status_code,
    outcome,
    secret_path_sha256
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING sequence, occurred_at, request_id, principal_id, method, route,
          status_code, outcome, secret_path_sha256
`

type InsertAuditEventParams struct {
	OccurredAt       string         `json:"occurred_at"`
	RequestID        string         `json:"request_id"`
	PrincipalID      sql.NullString `json:"principal_id"`
	Method           string         `json:"method"`
	Route            string         `json:"route"`
	StatusCode       int64          `json:"status_code"`
	Outcome          string         `json:"outcome"`
	SecretPathSha256 sql.NullString `json:"secret_path_sha256"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRowContext(ctx, insertAuditEvent,
		arg.OccurredAt,
		arg.RequestID,
		arg.PrincipalID,
		arg.Method,
		arg.Route,
		arg.StatusCode,
		arg.Outcome,
		arg.SecretPathSha256,
	)
	var i AuditEvent
	err := row.Scan(
		&i.Sequence,
		&i.OccurredAt,
		&i.RequestID,
		&i.PrincipalID,
		&i.Method,
		&i.Route,
		&i.StatusCode,
		&i.Outcome,
		&i.SecretPathSha256,
	)
	return i, err
}

const listAuditEventsPage = `-- name: ListAuditEventsPage :many
SELECT sequence, occurred_at, request_id, principal_id, method, route,
       status_code, outcome, secret_path_sha256
FROM audit_events
WHERE sequence > ?1
ORDER BY sequence
LIMIT ?2
`

type ListAuditEventsPageParams struct {
	AfterSequence int64 `json:"after_sequence"`
	PageSize      int64 `json:"page_size"`
}

func (q *Queries) ListAuditEventsPage(ctx context.Context, arg ListAuditEventsPageParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsPage, arg.AfterSequence, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.Sequence,
			&i.OccurredAt,
			&i.RequestID,
			&i.PrincipalID,
			&i.Method,
			&i.Route,
			&i.StatusCode,
			&i.Outcome,
			&i.SecretPathSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
