// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorization.sql

package sqlc

import (
	"context"
)

const advanceAuthorizationPolicyState = `-- name: AdvanceAuthorizationPolicyState :execrows
UPDATE authorization_policy_state
SET initialized = 1, revision = revision + 1
WHERE id = 1 AND revision = ?
`

func (q *Queries) AdvanceAuthorizationPolicyState(ctx context.Context, revision int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceAuthorizationPolicyState, revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAuthorizationPolicies = `-- name: DeleteAuthorizationPolicies :exec
DELETE FROM authorization_policies
`

func (q *Queries) DeleteAuthorizationPolicies(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAuthorizationPolicies)
	return err
}

const deleteAuthorizationRoleBindings = `-- name: DeleteAuthorizationRoleBindings :exec
DELETE FROM authorization_role_bindings
`

func (q *Queries) DeleteAuthorizationRoleBindings(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAuthorizationRoleBindings)
	return err
}

const getAuthorizationPolicyState = `-- name: GetAuthorizationPolicyState :one
SELECT id, initialized, revision
FROM authorization_policy_state
WHERE id = 1
`

func (q *Queries) GetAuthorizationPolicyState(ctx context.Context) (AuthorizationPolicyState, error) {
	row := q.db.QueryRowContext(ctx, getAuthorizationPolicyState)
	var i AuthorizationPolicyState
	err := row.Scan(&i.ID, &i.Initialized, &i.Revision)
	return i, err
}

const insertAuthorizationPolicy = `-- name: InsertAuthorizationPolicy :exec
INSERT INTO authorization_policies (subject, domain, path, method, secret_path_prefix)
VALUES (?, ?, ?, ?, ?)
`

type InsertAuthorizationPolicyParams struct {
	Subject          string `json:"subject"`
	Domain           string `json:"domain"`
	Path             string `json:"path"`
	Method           string `json:"method"`
	SecretPathPrefix string `json:"secret_path_prefix"`
}

func (q *Queries) InsertAuthorizationPolicy(ctx context.Context, arg InsertAuthorizationPolicyParams) error {
	_, err := q.db.ExecContext(ctx, insertAuthorizationPolicy,
		arg.Subject,
		arg.Domain,
		arg.Path,
		arg.Method,
		arg.SecretPathPrefix,
	)
	return err
}

const insertAuthorizationRoleBinding = `-- name: InsertAuthorizationRoleBinding :exec
INSERT INTO authorization_role_bindings (principal_id, role, domain)
VALUES (?, ?, ?)
`

type InsertAuthorizationRoleBindingParams struct {
	PrincipalID string `json:"principal_id"`
	Role        string `json:"role"`
	Domain      string `json:"domain"`
}

func (q *Queries) InsertAuthorizationRoleBinding(ctx context.Context, arg InsertAuthorizationRoleBindingParams) error {
	_, err := q.db.ExecContext(ctx, insertAuthorizationRoleBinding, arg.PrincipalID, arg.Role, arg.Domain)
	return err
}

const listAuthorizationPolicies = `-- name: ListAuthorizationPolicies :many
SELECT subject, domain, path, method, secret_path_prefix
FROM authorization_policies
ORDER BY subject, domain, path, method, secret_path_prefix
`

func (q *Queries) ListAuthorizationPolicies(ctx context.Context) ([]AuthorizationPolicy, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorizationPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthorizationPolicy{}
	for rows.Next() {
		var i AuthorizationPolicy
		if err := rows.Scan(
			&i.Subject,
			&i.Domain,
			&i.Path,
			&i.Method,
			&i.SecretPathPrefix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorizationRoleBindings = `-- name: ListAuthorizationRoleBindings :many
SELECT principal_id, role, domain
FROM authorization_role_bindings
ORDER BY principal_id, role, domain
`

func (q *Queries) ListAuthorizationRoleBindings(ctx context.Context) ([]AuthorizationRoleBinding, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorizationRoleBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthorizationRoleBinding{}
	for rows.Next() {
		var i AuthorizationRoleBinding
		if err := rows.Scan(&i.PrincipalID, &i.Role, &i.Domain); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
