// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: changes.sql

package sqlc

import (
	"context"
)

const getResourceVersion = `-- name: GetResourceVersion :one
SELECT revision
FROM moco_resource_version
WHERE id = 1
`

func (q *Queries) GetResourceVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getResourceVersion)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}
