// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: encryption.sql

package sqlc

import (
	"context"
)

const advanceEncryptionKeyState = `-- name: AdvanceEncryptionKeyState :execrows
UPDATE encryption_key_state
SET active_root_key_id = ?1,
    epoch = ?2
WHERE id = 1
  AND epoch = ?3
`

type AdvanceEncryptionKeyStateParams struct {
	ActiveRootKeyID string `json:"active_root_key_id"`
	NextEpoch       int64  `json:"next_epoch"`
	ExpectedEpoch   int64  `json:"expected_epoch"`
}

func (q *Queries) AdvanceEncryptionKeyState(ctx context.Context, arg AdvanceEncryptionKeyStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceEncryptionKeyState, arg.ActiveRootKeyID, arg.NextEpoch, arg.ExpectedEpoch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEncryptionKeyState = `-- name: GetEncryptionKeyState :one
SELECT active_root_key_id, epoch
FROM encryption_key_state
WHERE id = 1
`

type GetEncryptionKeyStateRow struct {
	ActiveRootKeyID string `json:"active_root_key_id"`
	Epoch           int64  `json:"epoch"`
}

func (q *Queries) GetEncryptionKeyState(ctx context.Context) (GetEncryptionKeyStateRow, error) {
	row := q.db.QueryRowContext(ctx, getEncryptionKeyState)
	var i GetEncryptionKeyStateRow
	err := row.Scan(&i.ActiveRootKeyID, &i.Epoch)
	return i, err
}
