// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type AuthorizationPolicy struct {
	Subject string `json:"subject"`
	Domain  string `json:"domain"`
	Path    string `json:"path"`
	Method  string `json:"method"`
}

type AuthorizationPolicyState struct {
	ID          int64 `json:"id"`
	Initialized int64 `json:"initialized"`
	Revision    int64 `json:"revision"`
}

type AuthorizationRoleBinding struct {
	PrincipalID string `json:"principal_id"`
	Role        string `json:"role"`
	Domain      string `json:"domain"`
}

type IdempotencyRecord struct {
	PrincipalID    string `json:"principal_id"`
	Operation      string `json:"operation"`
	IdempotencyKey string `json:"idempotency_key"`
	RequestHash    string `json:"request_hash"`
	StatusCode     int64  `json:"status_code"`
	ResourceID     string `json:"resource_id"`
	ResponseJson   []byte `json:"response_json"`
	ResponseEtag   string `json:"response_etag"`
	CreatedAt      string `json:"created_at"`
	ExpiresAt      string `json:"expires_at"`
}

type Secret struct {
	Sequence    int64  `json:"sequence"`
	TenantID    string `json:"tenant_id"`
	VaultID     string `json:"vault_id"`
	Path        string `json:"path"`
	Salt        []byte `json:"salt"`
	Ciphertext  []byte `json:"ciphertext"`
	Digest      string `json:"digest"`
	ContentType string `json:"content_type"`
	Version     int64  `json:"version"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type Tenant struct {
	Sequence    int64          `json:"sequence"`
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ExternalID  sql.NullString `json:"external_id"`
	LabelsJson  string         `json:"labels_json"`
	Revision    int64          `json:"revision"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

type Vault struct {
	Sequence    int64          `json:"sequence"`
	ID          string         `json:"id"`
	TenantID    string         `json:"tenant_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ExternalID  sql.NullString `json:"external_id"`
	LabelsJson  string         `json:"labels_json"`
	Revision    int64          `json:"revision"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

type VaultKey struct {
	TenantID   string `json:"tenant_id"`
	VaultID    string `json:"vault_id"`
	RootKeyID  string `json:"root_key_id"`
	Salt       []byte `json:"salt"`
	WrappedKey []byte `json:"wrapped_key"`
	CreatedAt  string `json:"created_at"`
}
