// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type IdempotencyRecord struct {
	PrincipalID    string `json:"principal_id"`
	Operation      string `json:"operation"`
	IdempotencyKey string `json:"idempotency_key"`
	RequestHash    string `json:"request_hash"`
	StatusCode     int64  `json:"status_code"`
	ResourceID     string `json:"resource_id"`
	ResponseJson   []byte `json:"response_json"`
	ResponseEtag   string `json:"response_etag"`
	CreatedAt      string `json:"created_at"`
	ExpiresAt      string `json:"expires_at"`
}

type Tenant struct {
	Sequence    int64          `json:"sequence"`
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ExternalID  sql.NullString `json:"external_id"`
	LabelsJson  string         `json:"labels_json"`
	Revision    int64          `json:"revision"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}
