// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package sqlc

import (
	"context"
)

const countVaultSecrets = `-- name: CountVaultSecrets :one
SELECT COUNT(*)
FROM secrets
WHERE tenant_id = ?1
  AND vault_id = ?2
`

type CountVaultSecretsParams struct {
	TenantID string `json:"tenant_id"`
	VaultID  string `json:"vault_id"`
}

func (q *Queries) CountVaultSecrets(ctx context.Context, arg CountVaultSecretsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVaultSecrets, arg.TenantID, arg.VaultID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSecret = `-- name: DeleteSecret :execrows
DELETE FROM secrets
WHERE tenant_id = ?1
  AND vault_id = ?2
  AND path = ?3
`

type DeleteSecretParams struct {
	TenantID string `json:"tenant_id"`
	VaultID  string `json:"vault_id"`
	Path     string `json:"path"`
}

func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSecret, arg.TenantID, arg.VaultID, arg.Path)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSecretIfVersion = `-- name: DeleteSecretIfVersion :execrows
DELETE FROM secrets
WHERE tenant_id = ?1
  AND vault_id = ?2
  AND path = ?3
  AND version = ?4
`

type DeleteSecretIfVersionParams struct {
	TenantID        string `json:"tenant_id"`
	VaultID         string `json:"vault_id"`
	Path            string `json:"path"`
	ExpectedVersion int64  `json:"expected_version"`
}

func (q *Queries) DeleteSecretIfVersion(ctx context.Context, arg DeleteSecretIfVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSecretIfVersion,
		arg.TenantID,
		arg.VaultID,
		arg.Path,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSecretMetadata = `-- name: GetSecretMetadata :one
SELECT sequence, tenant_id, vault_id, path, digest, content_type, version,
       created_at, updated_at
FROM secrets
WHERE tenant_id = ?1
  AND vault_id = ?2
  AND path = ?3
LIMIT 1
`

type GetSecretMetadataParams struct {
	TenantID string `json:"tenant_id"`
	VaultID  string `json:"vault_id"`
	Path     string `json:"path"`
}

type GetSecretMetadataRow struct {
	Sequence    int64  `json:"sequence"`
	TenantID    string `json:"tenant_id"`
	VaultID     string `json:"vault_id"`
	Path        string `json:"path"`
	Digest      string `json:"digest"`
	ContentType string `json:"content_type"`
	Version     int64  `json:"version"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) GetSecretMetadata(ctx context.Context, arg GetSecretMetadataParams) (GetSecretMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getSecretMetadata, arg.TenantID, arg.VaultID, arg.Path)
	var i GetSecretMetadataRow
	err := row.Scan(
		&i.Sequence,
		&i.TenantID,
		&i.VaultID,
		&i.Path,
		&i.Digest,
		&i.ContentType,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecretRecord = `-- name: GetSecretRecord :one
SELECT secrets.sequence,
       secrets.tenant_id,
       secrets.vault_id,
       secrets.path,
       secrets.salt AS secret_salt,
       secrets.ciphertext,
       secrets.digest,
       secrets.content_type,
       secrets.version,
       secrets.created_at,
       secrets.updated_at,
       vault_keys.root_key_id,
       vault_keys.salt AS key_salt,
       vault_keys.wrapped_key,
       vault_keys.created_at AS key_created_at
FROM secrets
JOIN vault_keys
  ON vault_keys.tenant_id = secrets.tenant_id
 AND vault_keys.vault_id = secrets.vault_id
WHERE secrets.tenant_id = ?1
  AND secrets.vault_id = ?2
  AND secrets.path = ?3
LIMIT 1
`

type GetSecretRecordParams struct {
	TenantID string `json:"tenant_id"`
	VaultID  string `json:"vault_id"`
	Path     string `json:"path"`
}

type GetSecretRecordRow struct {
	Sequence     int64  `json:"sequence"`
	TenantID     string `json:"tenant_id"`
	VaultID      string `json:"vault_id"`
	Path         string `json:"path"`
	SecretSalt   []byte `json:"secret_salt"`
	Ciphertext   []byte `json:"ciphertext"`
	Digest       string `json:"digest"`
	ContentType  string `json:"content_type"`
	Version      int64  `json:"version"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
	RootKeyID    string `json:"root_key_id"`
	KeySalt      []byte `json:"key_salt"`
	WrappedKey   []byte `json:"wrapped_key"`
	KeyCreatedAt string `json:"key_created_at"`
}

func (q *Queries) GetSecretRecord(ctx context.Context, arg GetSecretRecordParams) (GetSecretRecordRow, error) {
	row := q.db.QueryRowContext(ctx, getSecretRecord, arg.TenantID, arg.VaultID, arg.Path)
	var i GetSecretRecordRow
	err := row.Scan(
		&i.Sequence,
		&i.TenantID,
		&i.VaultID,
		&i.Path,
		&i.SecretSalt,
		&i.Ciphertext,
		&i.Digest,
		&i.ContentType,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RootKeyID,
		&i.KeySalt,
		&i.WrappedKey,
		&i.KeyCreatedAt,
	)
	return i, err
}

const getVaultKey = `-- name: GetVaultKey :one
SELECT root_key_id, salt, wrapped_key, created_at
FROM vault_keys
WHERE tenant_id = ?1
  AND vault_id = ?2
LIMIT 1
`

type GetVaultKeyParams struct {
	TenantID string `json:"tenant_id"`
	VaultID  string `json:"vault_id"`
}

type GetVaultKeyRow struct {
	RootKeyID  string `json:"root_key_id"`
	Salt       []byte `json:"salt"`
	WrappedKey []byte `json:"wrapped_key"`
	CreatedAt  string `json:"created_at"`
}

func (q *Queries) GetVaultKey(ctx context.Context, arg GetVaultKeyParams) (GetVaultKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getVaultKey, arg.TenantID, arg.VaultID)
	var i GetVaultKeyRow
	err := row.Scan(
		&i.RootKeyID,
		&i.Salt,
		&i.WrappedKey,
		&i.CreatedAt,
	)
	return i, err
}

const insertSecret = `-- name: InsertSecret :one
INSERT INTO secrets (
    tenant_id,
    vault_id,
    path,
    salt,
    ciphertext,
    digest,
    content_type,
    version,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?, ?)
ON CONFLICT (tenant_id, vault_id, path) DO NOTHING
RETURNING sequence, tenant_id, vault_id, path, salt, ciphertext, digest,
          content_type, version, created_at, updated_at
`

type InsertSecretParams struct {
	TenantID    string `json:"tenant_id"`
	VaultID     string `json:"vault_id"`
	Path        string `json:"path"`
	Salt        []byte `json:"salt"`
	Ciphertext  []byte `json:"ciphertext"`
	Digest      string `json:"digest"`
	ContentType string `json:"content_type"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) InsertSecret(ctx context.Context, arg InsertSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, insertSecret,
		arg.TenantID,
		arg.VaultID,
		arg.Path,
		arg.Salt,
		arg.Ciphertext,
		arg.Digest,
		arg.ContentType,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Secret
	err := row.Scan(
		&i.Sequence,
		&i.TenantID,
		&i.VaultID,
		&i.Path,
		&i.Salt,
		&i.Ciphertext,
		&i.Digest,
		&i.ContentType,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVaultKey = `-- name: InsertVaultKey :execrows
INSERT INTO vault_keys (
    tenant_id,
    vault_id,
    root_key_id,
    salt,
    wrapped_key,
    created_at
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (tenant_id, vault_id) DO NOTHING
`

type InsertVaultKeyParams struct {
	TenantID   string `json:"tenant_id"`
	VaultID    string `json:"vault_id"`
	RootKeyID  string `json:"root_key_id"`
	Salt       []byte `json:"salt"`
	WrappedKey []byte `json:"wrapped_key"`
	CreatedAt  string `json:"created_at"`
}

func (q *Queries) InsertVaultKey(ctx context.Context, arg InsertVaultKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertVaultKey,
		arg.TenantID,
		arg.VaultID,
		arg.RootKeyID,
		arg.Salt,
		arg.WrappedKey,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listSecretMetadataPage = `-- name: ListSecretMetadataPage :many
SELECT sequence, tenant_id, vault_id, path, digest, content_type, version,
       created_at, updated_at
FROM secrets
WHERE tenant_id = ?1
  AND vault_id = ?2
  AND sequence > ?3
  AND sequence <= ?4
  AND (
      ?5 IS NULL
      OR substr(path, 1, length(?5)) = ?5
  )
ORDER BY sequence
LIMIT ?6
`

type ListSecretMetadataPageParams struct {
	TenantID         string      `json:"tenant_id"`
	VaultID          string      `json:"vault_id"`
	AfterSequence    int64       `json:"after_sequence"`
	SnapshotSequence int64       `json:"snapshot_sequence"`
	Prefix           interface{} `json:"prefix"`
	PageSize         int64       `json:"page_size"`
}

type ListSecretMetadataPageRow struct {
	Sequence    int64  `json:"sequence"`
	TenantID    string `json:"tenant_id"`
	VaultID     string `json:"vault_id"`
	Path        string `json:"path"`
	Digest      string `json:"digest"`
	ContentType string `json:"content_type"`
	Version     int64  `json:"version"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) ListSecretMetadataPage(ctx context.Context, arg ListSecretMetadataPageParams) ([]ListSecretMetadataPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listSecretMetadataPage,
		arg.TenantID,
		arg.VaultID,
		arg.AfterSequence,
		arg.SnapshotSequence,
		arg.Prefix,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretMetadataPageRow{}
	for rows.Next() {
		var i ListSecretMetadataPageRow
		if err := rows.Scan(
			&i.Sequence,
			&i.TenantID,
			&i.VaultID,
			&i.Path,
			&i.Digest,
			&i.ContentType,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const secretSnapshotUpperBound = `-- name: SecretSnapshotUpperBound :one
SELECT
    CAST(EXISTS(
        SELECT 1
        FROM vaults
        WHERE vaults.tenant_id = ?1
          AND vaults.id = ?2
    ) AS INTEGER) AS vault_exists,
    CAST(COALESCE(MAX(sequence), 0) AS INTEGER) AS max_sequence
FROM secrets
WHERE tenant_id = ?1
  AND vault_id = ?2
`

type SecretSnapshotUpperBoundParams struct {
	TenantID string `json:"tenant_id"`
	VaultID  string `json:"vault_id"`
}

type SecretSnapshotUpperBoundRow struct {
	VaultExists int64 `json:"vault_exists"`
	MaxSequence int64 `json:"max_sequence"`
}

func (q *Queries) SecretSnapshotUpperBound(ctx context.Context, arg SecretSnapshotUpperBoundParams) (SecretSnapshotUpperBoundRow, error) {
	row := q.db.QueryRowContext(ctx, secretSnapshotUpperBound, arg.TenantID, arg.VaultID)
	var i SecretSnapshotUpperBoundRow
	err := row.Scan(&i.VaultExists, &i.MaxSequence)
	return i, err
}

const updateSecretIfVersion = `-- name: UpdateSecretIfVersion :one
UPDATE secrets
SET salt = ?1,
    ciphertext = ?2,
    digest = ?3,
    content_type = ?4,
    version = version + 1,
    updated_at = ?5
WHERE tenant_id = ?6
  AND vault_id = ?7
  AND path = ?8
  AND version = ?9
  AND (digest <> ?3 OR content_type <> ?4)
RETURNING sequence, tenant_id, vault_id, path, salt, ciphertext, digest,
          content_type, version, created_at, updated_at
`

type UpdateSecretIfVersionParams struct {
	Salt            []byte `json:"salt"`
	Ciphertext      []byte `json:"ciphertext"`
	Digest          string `json:"digest"`
	ContentType     string `json:"content_type"`
	UpdatedAt       string `json:"updated_at"`
	TenantID        string `json:"tenant_id"`
	VaultID         string `json:"vault_id"`
	Path            string `json:"path"`
	ExpectedVersion int64  `json:"expected_version"`
}

func (q *Queries) UpdateSecretIfVersion(ctx context.Context, arg UpdateSecretIfVersionParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, updateSecretIfVersion,
		arg.Salt,
		arg.Ciphertext,
		arg.Digest,
		arg.ContentType,
		arg.UpdatedAt,
		arg.TenantID,
		arg.VaultID,
		arg.Path,
		arg.ExpectedVersion,
	)
	var i Secret
	err := row.Scan(
		&i.Sequence,
		&i.TenantID,
		&i.VaultID,
		&i.Path,
		&i.Salt,
		&i.Ciphertext,
		&i.Digest,
		&i.ContentType,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSecret = `-- name: UpsertSecret :one
INSERT INTO secrets (
    tenant_id,
    vault_id,
    path,
    salt,
    ciphertext,
    digest,
    content_type,
    version,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?, ?)
ON CONFLICT (tenant_id, vault_id, path) DO UPDATE
SET salt = excluded.salt,
    ciphertext = excluded.ciphertext,
    digest = excluded.digest,
    content_type = excluded.content_type,
    version = secrets.version + 1,
    updated_at = excluded.updated_at
WHERE secrets.digest <> excluded.digest
   OR secrets.content_type <> excluded.content_type
RETURNING sequence, tenant_id, vault_id, path, salt, ciphertext, digest,
          content_type, version, created_at, updated_at
`

type UpsertSecretParams struct {
	TenantID    string `json:"tenant_id"`
	VaultID     string `json:"vault_id"`
	Path        string `json:"path"`
	Salt        []byte `json:"salt"`
	Ciphertext  []byte `json:"ciphertext"`
	Digest      string `json:"digest"`
	ContentType string `json:"content_type"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) UpsertSecret(ctx context.Context, arg UpsertSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, upsertSecret,
		arg.TenantID,
		arg.VaultID,
		arg.Path,
		arg.Salt,
		arg.Ciphertext,
		arg.Digest,
		arg.ContentType,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Secret
	err := row.Scan(
		&i.Sequence,
		&i.TenantID,
		&i.VaultID,
		&i.Path,
		&i.Salt,
		&i.Ciphertext,
		&i.Digest,
		&i.ContentType,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
