// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countTenantVaults = `-- name: CountTenantVaults :one
SELECT CAST(COUNT(*) AS INTEGER)
FROM vaults
WHERE tenant_id = ?
`

func (q *Queries) CountTenantVaults(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTenantVaults, tenantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteExpiredIdempotencyRecords = `-- name: DeleteExpiredIdempotencyRecords :exec
DELETE FROM idempotency_records
WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredIdempotencyRecords(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredIdempotencyRecords, expiresAt)
	return err
}

const deleteTenant = `-- name: DeleteTenant :execrows
DELETE FROM tenants
WHERE id = ?
`

func (q *Queries) DeleteTenant(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTenant, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTenantIfEmpty = `-- name: DeleteTenantIfEmpty :execrows
DELETE FROM tenants
WHERE tenants.id = ?
  AND NOT EXISTS (
      SELECT 1 FROM vaults WHERE vaults.tenant_id = tenants.id
  )
`

func (q *Queries) DeleteTenantIfEmpty(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTenantIfEmpty, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTenantIfRevision = `-- name: DeleteTenantIfRevision :execrows
DELETE FROM tenants
WHERE id = ?1
  AND revision = ?2
`

type DeleteTenantIfRevisionParams struct {
	ID               string `json:"id"`
	ExpectedRevision int64  `json:"expected_revision"`
}

func (q *Queries) DeleteTenantIfRevision(ctx context.Context, arg DeleteTenantIfRevisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTenantIfRevision, arg.ID, arg.ExpectedRevision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTenantIfRevisionAndEmpty = `-- name: DeleteTenantIfRevisionAndEmpty :execrows
DELETE FROM tenants
WHERE tenants.id = ?1
  AND tenants.revision = ?2
  AND NOT EXISTS (
      SELECT 1 FROM vaults WHERE vaults.tenant_id = tenants.id
  )
`

type DeleteTenantIfRevisionAndEmptyParams struct {
	ID               string `json:"id"`
	ExpectedRevision int64  `json:"expected_revision"`
}

func (q *Queries) DeleteTenantIfRevisionAndEmpty(ctx context.Context, arg DeleteTenantIfRevisionAndEmptyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTenantIfRevisionAndEmpty, arg.ID, arg.ExpectedRevision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findTenantConflict = `-- name: FindTenantConflict :one
SELECT id
FROM tenants
WHERE name = ?1
   OR (?2 IS NOT NULL AND external_id = ?2)
ORDER BY CASE WHEN name = ?1 THEN 0 ELSE 1 END
LIMIT 1
`

type FindTenantConflictParams struct {
	Name       string      `json:"name"`
	ExternalID interface{} `json:"external_id"`
}

func (q *Queries) FindTenantConflict(ctx context.Context, arg FindTenantConflictParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findTenantConflict, arg.Name, arg.ExternalID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getIdempotencyRecord = `-- name: GetIdempotencyRecord :one
SELECT principal_id, operation, idempotency_key, request_hash, status_code,
       resource_id, response_json, response_etag, created_at, expires_at
FROM idempotency_records
WHERE principal_id = ?1
  AND operation = ?2
  AND idempotency_key = ?3
LIMIT 1
`

type GetIdempotencyRecordParams struct {
	PrincipalID    string `json:"principal_id"`
	Operation      string `json:"operation"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (IdempotencyRecord, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyRecord, arg.PrincipalID, arg.Operation, arg.IdempotencyKey)
	var i IdempotencyRecord
	err := row.Scan(
		&i.PrincipalID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResourceID,
		&i.ResponseJson,
		&i.ResponseEtag,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT sequence, id, name, description, external_id, labels_json,
       revision, created_at, updated_at
FROM tenants
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetTenant(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.Sequence,
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.LabelsJson,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIdempotencyRecord = `-- name: InsertIdempotencyRecord :execrows
INSERT INTO idempotency_records (
    principal_id,
    operation,
    idempotency_key,
    request_hash,
    status_code,
    resource_id,
    response_json,
    response_etag,
    created_at,
    expires_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (principal_id, operation, idempotency_key) DO NOTHING
`

type InsertIdempotencyRecordParams struct {
	PrincipalID    string `json:"principal_id"`
	Operation      string `json:"operation"`
	IdempotencyKey string `json:"idempotency_key"`
	RequestHash    string `json:"request_hash"`
	StatusCode     int64  `json:"status_code"`
	ResourceID     string `json:"resource_id"`
	ResponseJson   []byte `json:"response_json"`
	ResponseEtag   string `json:"response_etag"`
	CreatedAt      string `json:"created_at"`
	ExpiresAt      string `json:"expires_at"`
}

func (q *Queries) InsertIdempotencyRecord(ctx context.Context, arg InsertIdempotencyRecordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertIdempotencyRecord,
		arg.PrincipalID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.StatusCode,
		arg.ResourceID,
		arg.ResponseJson,
		arg.ResponseEtag,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertTenant = `-- name: InsertTenant :one
INSERT INTO tenants (
    id,
    name,
    description,
    external_id,
    labels_json,
    revision,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING sequence, id, name, description, external_id, labels_json,
          revision, created_at, updated_at
`

type InsertTenantParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ExternalID  sql.NullString `json:"external_id"`
	LabelsJson  string         `json:"labels_json"`
	Revision    int64          `json:"revision"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, insertTenant,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ExternalID,
		arg.LabelsJson,
		arg.Revision,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Tenant
	err := row.Scan(
		&i.Sequence,
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.LabelsJson,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenantsPage = `-- name: ListTenantsPage :many
SELECT sequence, id, name, description, external_id, labels_json,
       revision, created_at, updated_at
FROM tenants
WHERE sequence > ?1
  AND sequence <= ?2
  AND (?3 IS NULL OR name = ?3)
  AND (?4 IS NULL OR external_id = ?4)
ORDER BY sequence
LIMIT ?5
`

type ListTenantsPageParams struct {
	AfterSequence    int64       `json:"after_sequence"`
	SnapshotSequence int64       `json:"snapshot_sequence"`
	Name             interface{} `json:"name"`
	ExternalID       interface{} `json:"external_id"`
	PageSize         int64       `json:"page_size"`
}

func (q *Queries) ListTenantsPage(ctx context.Context, arg ListTenantsPageParams) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, listTenantsPage,
		arg.AfterSequence,
		arg.SnapshotSequence,
		arg.Name,
		arg.ExternalID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.Sequence,
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ExternalID,
			&i.LabelsJson,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxTenantSequence = `-- name: MaxTenantSequence :one
SELECT CAST(COALESCE(MAX(sequence), 0) AS INTEGER)
FROM tenants
`

func (q *Queries) MaxTenantSequence(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxTenantSequence)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET name = ?1,
    description = ?2,
    labels_json = ?3,
    revision = revision + 1,
    updated_at = ?4
WHERE id = ?5
RETURNING sequence, id, name, description, external_id, labels_json,
          revision, created_at, updated_at
`

type UpdateTenantParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	LabelsJson  string         `json:"labels_json"`
	UpdatedAt   string         `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, updateTenant,
		arg.Name,
		arg.Description,
		arg.LabelsJson,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Tenant
	err := row.Scan(
		&i.Sequence,
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.LabelsJson,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantIfRevision = `-- name: UpdateTenantIfRevision :one
UPDATE tenants
SET name = ?1,
    description = ?2,
    labels_json = ?3,
    revision = revision + 1,
    updated_at = ?4
WHERE id = ?5
  AND revision = ?6
RETURNING sequence, id, name, description, external_id, labels_json,
          revision, created_at, updated_at
`

type UpdateTenantIfRevisionParams struct {
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	LabelsJson       string         `json:"labels_json"`
	UpdatedAt        string         `json:"updated_at"`
	ID               string         `json:"id"`
	ExpectedRevision int64          `json:"expected_revision"`
}

func (q *Queries) UpdateTenantIfRevision(ctx context.Context, arg UpdateTenantIfRevisionParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, updateTenantIfRevision,
		arg.Name,
		arg.Description,
		arg.LabelsJson,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedRevision,
	)
	var i Tenant
	err := row.Scan(
		&i.Sequence,
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.LabelsJson,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
