// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vaults.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteVault = `-- name: DeleteVault :execrows
DELETE FROM vaults
WHERE tenant_id = ?1
  AND id = ?2
`

type DeleteVaultParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) DeleteVault(ctx context.Context, arg DeleteVaultParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVault, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteVaultIfRevision = `-- name: DeleteVaultIfRevision :execrows
DELETE FROM vaults
WHERE tenant_id = ?1
  AND id = ?2
  AND revision = ?3
`

type DeleteVaultIfRevisionParams struct {
	TenantID         string `json:"tenant_id"`
	ID               string `json:"id"`
	ExpectedRevision int64  `json:"expected_revision"`
}

func (q *Queries) DeleteVaultIfRevision(ctx context.Context, arg DeleteVaultIfRevisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVaultIfRevision, arg.TenantID, arg.ID, arg.ExpectedRevision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findVaultConflict = `-- name: FindVaultConflict :one
SELECT id
FROM vaults
WHERE tenant_id = ?1
  AND (
      name = ?2
      OR (?3 IS NOT NULL AND external_id = ?3)
  )
ORDER BY CASE WHEN name = ?2 THEN 0 ELSE 1 END
LIMIT 1
`

type FindVaultConflictParams struct {
	TenantID   string      `json:"tenant_id"`
	Name       string      `json:"name"`
	ExternalID interface{} `json:"external_id"`
}

func (q *Queries) FindVaultConflict(ctx context.Context, arg FindVaultConflictParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findVaultConflict, arg.TenantID, arg.Name, arg.ExternalID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getVault = `-- name: GetVault :one
SELECT sequence, id, tenant_id, name, description, external_id, labels_json,
       revision, created_at, updated_at
FROM vaults
WHERE vaults.tenant_id = ?1
  AND vaults.id = ?2
LIMIT 1
`

type GetVaultParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetVault(ctx context.Context, arg GetVaultParams) (Vault, error) {
	row := q.db.QueryRowContext(ctx, getVault, arg.TenantID, arg.ID)
	var i Vault
	err := row.Scan(
		&i.Sequence,
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.LabelsJson,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVault = `-- name: InsertVault :one
INSERT INTO vaults (
    id,
    tenant_id,
    name,
    description,
    external_id,
    labels_json,
    revision,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING sequence, id, tenant_id, name, description, external_id, labels_json,
          revision, created_at, updated_at
`

type InsertVaultParams struct {
	ID          string         `json:"id"`
	TenantID    string         `json:"tenant_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ExternalID  sql.NullString `json:"external_id"`
	LabelsJson  string         `json:"labels_json"`
	Revision    int64          `json:"revision"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

func (q *Queries) InsertVault(ctx context.Context, arg InsertVaultParams) (Vault, error) {
	row := q.db.QueryRowContext(ctx, insertVault,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.ExternalID,
		arg.LabelsJson,
		arg.Revision,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Vault
	err := row.Scan(
		&i.Sequence,
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.LabelsJson,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVaultsPage = `-- name: ListVaultsPage :many
SELECT sequence, id, tenant_id, name, description, external_id, labels_json,
       revision, created_at, updated_at
FROM vaults
WHERE tenant_id = ?1
  AND sequence > ?2
  AND sequence <= ?3
  AND (?4 IS NULL OR name = ?4)
  AND (?5 IS NULL OR external_id = ?5)
ORDER BY sequence
LIMIT ?6
`

type ListVaultsPageParams struct {
	TenantID         string      `json:"tenant_id"`
	AfterSequence    int64       `json:"after_sequence"`
	SnapshotSequence int64       `json:"snapshot_sequence"`
	Name             interface{} `json:"name"`
	ExternalID       interface{} `json:"external_id"`
	PageSize         int64       `json:"page_size"`
}

func (q *Queries) ListVaultsPage(ctx context.Context, arg ListVaultsPageParams) ([]Vault, error) {
	rows, err := q.db.QueryContext(ctx, listVaultsPage,
		arg.TenantID,
		arg.AfterSequence,
		arg.SnapshotSequence,
		arg.Name,
		arg.ExternalID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vault{}
	for rows.Next() {
		var i Vault
		if err := rows.Scan(
			&i.Sequence,
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.ExternalID,
			&i.LabelsJson,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVault = `-- name: UpdateVault :one
UPDATE vaults
SET name = ?1,
    description = ?2,
    labels_json = ?3,
    revision = revision + 1,
    updated_at = ?4
WHERE tenant_id = ?5
  AND id = ?6
RETURNING sequence, id, tenant_id, name, description, external_id, labels_json,
          revision, created_at, updated_at
`

type UpdateVaultParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	LabelsJson  string         `json:"labels_json"`
	UpdatedAt   string         `json:"updated_at"`
	TenantID    string         `json:"tenant_id"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateVault(ctx context.Context, arg UpdateVaultParams) (Vault, error) {
	row := q.db.QueryRowContext(ctx, updateVault,
		arg.Name,
		arg.Description,
		arg.LabelsJson,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	var i Vault
	err := row.Scan(
		&i.Sequence,
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.LabelsJson,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVaultIfRevision = `-- name: UpdateVaultIfRevision :one
UPDATE vaults
SET name = ?1,
    description = ?2,
    labels_json = ?3,
    revision = revision + 1,
    updated_at = ?4
WHERE tenant_id = ?5
  AND id = ?6
  AND revision = ?7
RETURNING sequence, id, tenant_id, name, description, external_id, labels_json,
          revision, created_at, updated_at
`

type UpdateVaultIfRevisionParams struct {
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	LabelsJson       string         `json:"labels_json"`
	UpdatedAt        string         `json:"updated_at"`
	TenantID         string         `json:"tenant_id"`
	ID               string         `json:"id"`
	ExpectedRevision int64          `json:"expected_revision"`
}

func (q *Queries) UpdateVaultIfRevision(ctx context.Context, arg UpdateVaultIfRevisionParams) (Vault, error) {
	row := q.db.QueryRowContext(ctx, updateVaultIfRevision,
		arg.Name,
		arg.Description,
		arg.LabelsJson,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
		arg.ExpectedRevision,
	)
	var i Vault
	err := row.Scan(
		&i.Sequence,
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ExternalID,
		&i.LabelsJson,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const vaultSnapshotUpperBound = `-- name: VaultSnapshotUpperBound :one
SELECT
    CAST(EXISTS(SELECT 1 FROM tenants WHERE tenants.id = ?1) AS INTEGER) AS tenant_exists,
    CAST(COALESCE(MAX(sequence), 0) AS INTEGER) AS max_sequence
FROM vaults
WHERE tenant_id = ?1
`

type VaultSnapshotUpperBoundRow struct {
	TenantExists int64 `json:"tenant_exists"`
	MaxSequence  int64 `json:"max_sequence"`
}

func (q *Queries) VaultSnapshotUpperBound(ctx context.Context, tenantID string) (VaultSnapshotUpperBoundRow, error) {
	row := q.db.QueryRowContext(ctx, vaultSnapshotUpperBound, tenantID)
	var i VaultSnapshotUpperBoundRow
	err := row.Scan(&i.TenantExists, &i.MaxSequence)
	return i, err
}
